// src/components/SearchBar.svelte
<script lang="ts">
    import Fuse from "fuse.js";
    import { animeVostFr, animesVostFr } from "../stores/animeStore";

    let input: string;

    const fuse = new Fuse($animeVostFr, {
        keys: ["title", "id", "title_english", "title_romanji", "others"]
    });

    async function search() {
        let lastInput = input;
        let isOk = false;
        
        await new Promise((resolve) => {
            setTimeout(() => {
                if (lastInput == input) isOk = true;
                resolve(null)
            }, 300);
        });

        if (isOk) {
            const result = fuse.search(input).map(result => result.item);

            if (result.length <= 0) {
                $animeVostFr = $animesVostFr;
                return;
            }

            $animeVostFr = result;
        }
    }
</script>

<input on:keyup={search} bind:value={input} type="text" class="w-full p-3 bg-zinc-800 focus:outline-none mb-5" placeholder="rechercher un anime...">

// src/components/SearchBarComponent.vue
<script lang="ts">
import { animesStore } from '@/stores/animeStore';
import { removeDuplicates } from "@/utils/removeDuplicates";
import Fuse from 'fuse.js';

export default {
    data() {
        return {
            query: '',
        };
    },

    methods: {
        async search() {
            console.log("test");
            let oldQuery = this.query;

            await new Promise(function (ok) {
                setTimeout(function () {
                    ok(null);
                }, 500);
            });

            if (oldQuery !== this.query) return;
            const fuse = new Fuse(animesStore.all, {
                keys: ['title', 'title_english', 'title_romanji', 'genres', 'others', 'id'],
            });
            const result = fuse.search(this.query);
            const finaLResult = removeDuplicates(result.map((a) => a.item));
            animesStore.result = finaLResult.length > 0 ? finaLResult : animesStore.all;
        },
    },
};
</script>

<template>
    <input type="text" @input="search" v-model="query" placeholder="rechercher un anime..." class="w-full p-5 bg-zinc-800 rounded my-5 focus:outline-none">
</template>
